jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Умный кэш для Go (теперь найдет go.sum)
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true
          cache-dependency-path: 'appctr/go.sum'

      # 2. Настраиваем Java и кэшируем зависимости Gradle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # 3. Кэшируем Android SDK/NDK, чтобы не качать гигабайты каждый раз
      - name: Cache Android SDK/NDK
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ${{ runner.os }}-android-ndk-${{ hashFiles('app/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-android-ndk-

      
      # 4. Кэшируем бинарник gomobile
      - name: Cache gomobile
        uses: actions/cache@v4
        with:
          path: ~/go/bin/gomobile
          key: ${{ runner.os }}-gomobile-${{ hashFiles('appctr/go.mod') }}
          
      - name: Install gomobile
        run: |
          if ! command -v gomobile &> /dev/null; then
            go install golang.org/x/mobile/cmd/gomobile@latest
            gomobile init
          fi